# Generated by Django 3.2.9 on 2023-04-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chats_id', models.AutoField(default=1000, primary_key=True, serialize=False, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_login', models.CharField(max_length=100, verbose_name='Логин')),
                ('user_permission', models.BooleanField(default=False, verbose_name='ТехПоддержка')),
                ('user_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт в системе')),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messages_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.CharField(max_length=300, verbose_name='Текст')),
                ('messages_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chats', verbose_name='Чат')),
                ('messages_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='chats_teh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_teh', to='api.users', verbose_name='ТехПоддержка'),
        ),
        migrations.AddField(
            model_name='chats',
            name='chats_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_user', to='api.users', verbose_name='Пользователь'),
        ),
    ]
