# Generated by Django 3.2.9 on 2023-04-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message_text',
            new_name='messages_text',
        ),
    ]
