# Generated by Django 3.2.9 on 2023-04-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230427_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='chats_tag',
            field=models.CharField(default='Другое', max_length=20, verbose_name='Тэг'),
            preserve_default=False,
        ),
    ]
