# Generated by Django 3.2.9 on 2023-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chats_chats_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='messages_text',
            field=models.TextField(max_length=500, verbose_name='Текст'),
        ),
    ]
